In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [2]:
# Load processed dataset

df = pd.read_csv("../data/processed/processed_dataset.csv")

print("Processed Dataset Loaded Successfully")

df.head()

Processed Dataset Loaded Successfully

,URL,URLLength,DomainLength,IsDomainIP,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,NoOfSubDomain,HasObfuscation,...,HasPasswordField,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfExternalRef,label
0,https://www.southbankmosaics.com,31,24,0,100.0,1.000000,0.522907,0.061933,1,0,...,0,1,0,0,1,34,20,28,124,1
1,https://www.uni-mainz.de,23,16,0,100.0,0.666667,0.032650,0.050207,1,0,...,0,0,0,0,1,50,9,8,217,1
2,https://www.voicefmradio.co.uk,29,22,0,100.0,0.866667,0.028555,0.064129,2,0,...,0,0,0,0,1,10,2,7,5,1
3,https://www.sfnmjournal.com,26,19,0,100.0,1.000000,0.522907,0.057606,1,0,...,0,0,1,1,1,3,27,15,31,1
4,https://www.rewildingargentina.org,33,26,0,100.0,1.000000,0.079963,0.059441,1,0,...,0,1,1,0,1,244,15,34,85,1

In [3]:
print("Dataset Shape:")

print(df.shape)

Dataset Shape:
(235795, 36)

In [4]:
df.columns

Index(['URL', 'URLLength', 'DomainLength', 'IsDomainIP', 'URLSimilarityIndex',
       'CharContinuationRate', 'TLDLegitimateProb', 'URLCharProb',
       'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar',
       'NoOfLettersInURL', 'NoOfDegitsInURL', 'NoOfOtherSpecialCharsInURL',
       'IsHTTPS', 'HasTitle', 'DomainTitleMatchScore', 'URLTitleMatchScore',
       'HasFavicon', 'Robots', 'IsResponsive', 'NoOfURLRedirect',
       'HasDescription', 'HasSocialNet', 'HasSubmitButton', 'HasHiddenFields',
       'HasPasswordField', 'Bank', 'Pay', 'Crypto', 'HasCopyrightInfo',
       'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfExternalRef', 'label'],
      dtype='str')

In [3]:
# Separate Features and Target

X = df.drop(columns=["label"])

y = df["label"]

print("Features Shape :", X.shape)
print("Target Shape   :", y.shape)

Features Shape : (235795, 35)
Target Shape   : (235795,)

In [6]:
X.head()

,URL,URLLength,DomainLength,IsDomainIP,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,NoOfSubDomain,HasObfuscation,...,HasHiddenFields,HasPasswordField,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfExternalRef
0,https://www.southbankmosaics.com,31,24,0,100.0,1.000000,0.522907,0.061933,1,0,...,1,0,1,0,0,1,34,20,28,124
1,https://www.uni-mainz.de,23,16,0,100.0,0.666667,0.032650,0.050207,1,0,...,0,0,0,0,0,1,50,9,8,217
2,https://www.voicefmradio.co.uk,29,22,0,100.0,0.866667,0.028555,0.064129,2,0,...,1,0,0,0,0,1,10,2,7,5
3,https://www.sfnmjournal.com,26,19,0,100.0,1.000000,0.522907,0.057606,1,0,...,1,0,0,1,1,1,3,27,15,31
4,https://www.rewildingargentina.org,33,26,0,100.0,1.000000,0.079963,0.059441,1,0,...,1,0,1,1,0,1,244,15,34,85

In [7]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: label, dtype: int64

In [4]:
X.dtypes

URL                               str
URLLength                       int64
DomainLength                    int64
IsDomainIP                      int64
URLSimilarityIndex            float64
CharContinuationRate          float64
TLDLegitimateProb             float64
URLCharProb                   float64
NoOfSubDomain                   int64
HasObfuscation                  int64
NoOfObfuscatedChar              int64
NoOfLettersInURL                int64
NoOfDegitsInURL                 int64
NoOfOtherSpecialCharsInURL      int64
IsHTTPS                         int64
HasTitle                        int64
DomainTitleMatchScore         float64
URLTitleMatchScore            float64
HasFavicon                      int64
Robots                          int64
IsResponsive                    int64
NoOfURLRedirect                 int64
HasDescription                  int64
HasSocialNet                    int64
HasSubmitButton                 int64
HasHiddenFields                 int64
HasPasswordField                int64
Bank                            int64
Pay                             int64
Crypto                          int64
HasCopyrightInfo                int64
NoOfImage                       int64
NoOfCSS                         int64
NoOfJS                          int64
NoOfExternalRef                 int64
dtype: object

In [5]:
# Remove URL column

X = X.drop("URL", axis=1)

print(X.shape)

(235795, 34)

In [6]:
X.dtypes

URLLength                       int64
DomainLength                    int64
IsDomainIP                      int64
URLSimilarityIndex            float64
CharContinuationRate          float64
TLDLegitimateProb             float64
URLCharProb                   float64
NoOfSubDomain                   int64
HasObfuscation                  int64
NoOfObfuscatedChar              int64
NoOfLettersInURL                int64
NoOfDegitsInURL                 int64
NoOfOtherSpecialCharsInURL      int64
IsHTTPS                         int64
HasTitle                        int64
DomainTitleMatchScore         float64
URLTitleMatchScore            float64
HasFavicon                      int64
Robots                          int64
IsResponsive                    int64
NoOfURLRedirect                 int64
HasDescription                  int64
HasSocialNet                    int64
HasSubmitButton                 int64
HasHiddenFields                 int64
HasPasswordField                int64
Bank                            int64
Pay                             int64
Crypto                          int64
HasCopyrightInfo                int64
NoOfImage                       int64
NoOfCSS                         int64
NoOfJS                          int64
NoOfExternalRef                 int64
dtype: object

In [8]:
print(X.shape)

(235795, 34)